name = "vesviet"
compatibility_date = "2024-04-11"
workers_dev = true

[[routes]]
pattern = "tanhdev.com"
custom_domain = true

[[routes]]
pattern = "www.tanhdev.com"
custom_domain = true

[assets]
directory = "public"
