name = "vesviet"
compatibility_date = "2025-04-01"
main = "src/index.js"
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "tanhdev.com"
custom_domain = true

[[routes]]
pattern = "www.tanhdev.com"
custom_domain = true

[assets]
directory = "public"
